control0:
  ros__parameters:
    runner_cutter_control_params:
      camera_node_name: "camera0"
      laser_node_name: "laser0"
      tracking_laser_color: [0.15, 0.0, 0.0]
      burn_laser_color: [0.0, 0.0, 1.0]
      burn_time_secs: 5
camera0:
  ros__parameters:
    camera_control_params:
      camera_type: "lucid"
      camera_index: 0
      fps: 30
      rgb_size: [1280, 720]
      depth_size: [1280, 720]
laser0:
  ros__parameters:
    laser_control_params:
      dac_type: "helios"
      dac_index: 0
      fps: 30
      pps: 30000
      transition_duration_ms: 0.5
