control0:
  ros__parameters:
    camera_node_name: "camera0"
    laser_node_name: "laser0"
    tracking_laser: [0.2, 0.0, 0.0]
    burn_color: [0.0, 0.0, 1.0]
    burn_time_secs: 5
camera0:
  ros__parameters:
    camera_index: 0
    fps: 10
    rgb_size: [1280, 720]
    depth_size: [1280, 720]
laser0:
  ros__parameters:
    dac_type: "helios"
    dac_index: 0
    fps: 30
    pps: 30000
    transition_duration_ms: 0.5
