port: 7880
log_level: info
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  stun_servers: []
  ips:
    excludes:
      - 172.16.0.0/12 # Docker bridge ranges (172.17-172.31)
      - 127.0.0.0/8
redis:
  address: 127.0.0.1:6379
ingress:
  rtmp_base_url: rtmp://localhost:1935
  whip_base_url: http://localhost:8085/whip
