# Usage:
#   docker compose up -d               # start containers
#   docker exec -it ros2-ros2-1 bash   # drop into shell for the running ros2 container
#   /entrypoint.sh                     # build and run nodes
#   exit                               # exits shell session
#   docker compose down                # stop containers
#
# Incremental rebuilds (C++ nodes only. Python nodes are live via symlink-install):
#   colcon build --packages-select <pkg> --no-clean

services:
  ros2:
    image: laser-runner-cutter-ros2:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        L4T_VERSION: r36.4.0
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true  # gives access to all /dev/*. In the future could specify devices.
    stop_grace_period: 10s # gives ROS nodes time to shut down cleanly
    depends_on:
      - redis
      - livekit-server
      - livekit-ingress
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      # Jetson library passthroughs required for CUDA in Docker on Jetson
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra # core CUDA/OpenGL libs
      - /usr/src/jetson_multimedia_api:/usr/src/jetson_multimedia_api # multimedia API headers
      - /usr/share/vpi3:/usr/share/vpi3 # NVIDIA VPI
      # Bind mount src and third_party
      - ./src:/workspaces/ros2/src
      - ./third_party:/workspaces/ros2/third_party
      # Keep build artifacts in volume mount to keep them across restarts while avoid polluting host
      - ros2-build:/workspaces/ros2/build
      - ros2-install:/workspaces/ros2/install
    env_file:
      - ../.env
    entrypoint: ["sleep", "infinity"]  # just keep container running forever
    restart: unless-stopped

  redis:
    image: redis:8
    network_mode: host
    restart: unless-stopped

  livekit-server:
    image: livekit/livekit-server:v1.11
    network_mode: host
    depends_on:
      - redis
    command: ["--config", "/config/livekit_server.yaml"]
    volumes:
      - ./src/livekit_ros2/config:/config:ro
    env_file:
      - ../.env # uses LIVEKIT_KEYS
    restart: unless-stopped

  livekit-ingress:
    image: livekit/ingress:v1.5
    network_mode: host
    depends_on:
      - livekit-server
      - redis
    command: ["--config", "/config/ingress_server.yaml"]
    volumes:
      - ./src/livekit_ros2/config:/config:ro
    env_file:
      - ../.env # uses LIVEKIT_API_KEY, LIVEKIT_API_SECRET
    restart: unless-stopped

volumes:
  ros2-build:
  ros2-install:
