furrow_perceiver_forward:
  ros__parameters:
    # Since RealSense ROS nodes are not using aioros2, we use a stub node def to represent the
    # dependency. We set the name of the dependent node here so that the topic names are resolved
    # properly.
    realsense_node:
      name: cam_forward
furrow_perceiver_backward:
  ros__parameters:
    # Since RealSense ROS nodes are not using aioros2, we use a stub node def to represent the
    # dependency. We set the name of the dependent node here so that the topic names are resolved
    # properly.
    realsense_node:
      name: cam_backward
